### PR TITLE
Making the router slash-tolerant to fix memory-store

### LINKED ISSUE #1: memory-store example 404s on callback due to trailing slash
image

Got a 404, "No webpage was found for the web address: `http://localhost:3000/signup/oauth/github/?code=blahdeeblahdeeblah`"

Looks like this route from `routes.rs` should be matching: 
https://github.com/StefanTerdell/userp/blob/main/src/routes.rs#L51

```rust
            signup_oauth_provider: "/signup/oauth/:provider",
```

It worked when I deleted the trailing slash: `http://localhost:3000/signup/oauth/github?code=blahdeeblahdeeblah`

I think I'd rather it be tolerant of trailing slashes? What do you think?

The dashboard after I fixed the URL, token redacted:

image

### PR DESCRIPTION
**Pull request by bitemyapp**
Fixes #1

### CODE REVIEW

**Comment by StefanTerdell** [comment]
Hi @bitemyapp! Thanks for opening a PR and offically becoming the first collaborator! Hope you're not the last :D

I'm wondering if we shouldn't leave this up to the user and the app initialization, though. We do have a dependency on tower-http already, so we could re-export  tower_http::normalize_path::NormalizePathLayer and include it in the examples, to be used as per the stackoverflow discussion.

Or we can merge this solution, but then please change `router.slash_router(...` to `router.slash_route(...` ;)

WDYT?

**Comment by bitemyapp** [comment]
The example app is broken at the moment regardless, so I definitely want to get it into a state where it works out of the box.

Let me try the tower middleware and see how it goes, looks potentially cleaner. I think there might be a perf trade-off in using middleware?

**Comment by bitemyapp** [comment]
The tower based normalization middleware seems like it's working, but now I get this error when I try to test the GitHub auth locally:

image

I wasn't getting this on Saturday.

Audit log shows it doing roughly the same things on Saturday and today, I see the app authorized in my list, so I'd tend to believe it's the redirect handler or something? I'm unsure.

**Comment by bitemyapp** [comment]
Revoked the app, re-did it, seemed to do the tripod successfully but something weird is happening with the redirect now? I'm so confused, it was working fine before and showed the detail page previously.

**Comment by bitemyapp** [comment]
[slash-tolerant.txt](https://github.com/user-attachments/files/17465028/slash-tolerant.txt)

Patch attached, GitHub made me rename the `.patch` to `.txt`. I had to add `tower-layer` for the layering. The router changes are back to vanilla apart from the commented out bit.

**Comment by bitemyapp** [comment]
Rebased

**Comment by bitemyapp** [comment]
```
thread 'main' panicked at examples/memory-store/src/main.rs:39:38:
Missing required env var: SMTP_URL
```

Getting this now trying to run `memory-store`. I changed the dependency to exclude this:

`userp = { path = "../../", default-features = false, features = ["axum", "oauth", "password"]}`

And it's saying it still wants the 5th function argument for `UserpConfig::new`, noodling through.

**Comment by bitemyapp** [comment]
Oh I see what's happening, axum is pulling in axum-router, axum-router is pulling in email. I just want a clean social auth wrapper and some Leptos components, I'm going to need to think about this. I don't want to stand up an SMTP server so that I can test a memory-only example for exercising social auth.

**Comment by StefanTerdell** [comment]
Noted! Thanks for your time. The template router requires all features at the moment since the templates themselves are not granular yet. Looking into this right now! Do note that there are no Leptos components available yet either though; this is planned once the base lib is in good shape. I will tag you again once:
1. The templates and router is fully granular, so you can leave out SMTP
2. Axum is fully separated and ready to be replaced by Actix

**Comment by bitemyapp** [comment]
@StefanTerdell would it be possible for you to make an example that just uses the OAuth callbacks and ignores templating/web frameworks entirely? I think if I had that I could add the providers & (optional) leptos components I'm looking for.

**Comment by bitemyapp** [comment]
Amending the previous reply: I'm going to see if I can make an example that strips down `memory-store` to just the OAuth components.

**Comment by bitemyapp** [comment]
Update: it breaks the session/cookie-store stuff if you try to keep it to oauth-only at present. Decomplecting this is possible but I'm looking for a minimal oauth client that already has Google and Apple implemented. I've implemented integrations privately for logging in with Google and Apple but they're gnarly and don't have things like token refresh yet.

I've been looking into https://github.com/bk-rs/oauth2-rs but the repo is oddly quiet and I haven't seen anyone mention it anywhere.

**Comment by StefanTerdell** [comment]
That sounds like something outside of the stated goal of this crate, given the necessity to handle cookies in one way or another to keep track of the logged in user session ID. A minimal OAuth only example is coming up as soon as possible though :)

**Comment by StefanTerdell** [comment]
Hello again! I manually added slash routes to the callback paths since these seem to be the only ones where you don't necessarily control the formatting as an end user. I also added granular templates by feature flags. I think that should cover the concerns of this PR so I'm closing this for now.

Please use the issue for further discussion, and thanks again for the contribution!

**Pull request closed without merging**
